language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -f udagram-reverse-proxy/Dockerfile -t udagram-reverse-proxy .
  - docker tag udagram-reverse-proxy tuxan/udagram-reverse-proxy:latest
  - docker build -f udagram-api-feed/Dockerfile -t udagram-api-feed .
  - docker tag udagram-api-feed tuxan/udagram-api-feed:latest
  - docker build -f udagram-api-user/Dockerfile -t udagram-api-user .
  - docker tag udagram-api-user tuxan/udagram-api-user:latest
  - docker build -f udagram-frontend/Dockerfile -t udagram-frontend .
  - docker tag udagram-frontend tuxan/udagram-frontend:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tuxan/udagram-reverse-proxy
  - docker push tuxan/udagram-api-feed
  - docker push tuxan/udagram-api-user
  - docker push tuxan/udagram-frontend