version: "3.8"
services:
  reverse-proxy:
    build:
      context: ../../reverse-proxy
    image: tuxan/udagram-reverse-proxy
  api-user:
    build:
      context: ../../api-user
    image: tuxan/udagram-api-user
  api-feed:
    build:
      context: ../../api-feed
    image: tuxan/udagram-api-feed
  frontend:
    build:
      context: ../../frontend
    image: tuxan/udagram-frontend