apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api-feed
  name: api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      service: api-feed
  template:
    metadata:
      labels:
        service: api-feed
    spec:
      containers:
      - image: tuxan/udagram-api-feed
        name: api-feed
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
              name: env-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret